CREATE TABLE scans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(512) NOT NULL,
  device_id VARCHAR(64) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  synced TINYINT(1) DEFAULT 0
);

